# Generated by Django 5.0.2 on 2024-03-07 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexApp', '0002_alter_visit_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_patient', to='complexApp.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('occupied', 'Occupied'), ('passed', 'Passed')], default='free', max_length=10),
        ),
    ]
