# Generated by Django 5.0.2 on 2024-03-07 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexApp', '0003_alter_visit_patient_alter_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complexApp.patient'),
        ),
    ]
