# Generated by Django 5.0.2 on 2024-03-14 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexApp', '0004_alter_visit_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='visit',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexApp.visitname'),
        ),
    ]
