# Generated by Django 5.0.2 on 2024-03-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexApp', '0005_visitname_alter_visit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitname',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
