# Generated by Django 5.0.2 on 2024-03-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexApp', '0006_alter_visitname_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='progress',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='results',
            new_name='recommendation',
        ),
    ]
