# Generated by Django 5.0.2 on 2024-03-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexApp', '0007_rename_progress_visit_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('occupied', 'Occupied'), ('passed', 'Passed'), ('in_process', 'In_Process')], default='free', max_length=10),
        ),
    ]
